public class Test{
    public static void main(String[] args){
        // Gorilla TEST
        Gorilla kiKong = new Gorilla();
        kiKong.throwSomething();
        kiKong.throwSomething();
        kiKong.throwSomething();
        kiKong.eatBananas();
        kiKong.eatBananas();
        kiKong.climb();
        kiKong.Display();
        // BAT TEST
        Bat dracula = new Bat();
        dracula.attackTown();
        dracula.attackTown();
        dracula.attackTown();
        dracula.eatHumans();
        dracula.eatHumans();
        dracula.fly();
        dracula.Display();
    }
}